version: "3"
services:
  master:
    build: .
    ports:
    - "8081:8080"
    environment:
      JAVA_OPTS: "-Xmx2048m"
    env_file:
      - ./env/master/secrets.env
    volumes:
    - jenkins-master:/var/jenkins_home
    - ./jenkins-config/:/var/jenkins_home/casc_configs/

  worker:
    depends_on:
    - master
    image: jenkins/jnlp-agent-docker
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_URL: http://master:8080/
      JENKINS_TUNNEL: master:50000
      JENKINS_AGENT_NAME: agent-slave
      JENKINS_AGENT_WORKDIR: .
    env_file:
      - ./env/worker/secrets.env
    restart: always
    volumes:
    - jenkins-worker:/var/jenkins_home/worker

volumes:
  jenkins-master:
    external:
      true
  jenkins-worker:
    external:
      true
